---

# ---------------------------------------
#          Start CIS Audit Script
# ---------------------------------------
- ping:
  register: connection_check
  ignore_errors: True
  retries: False

- name: Host name
  debug: var=ansible_all_ipv4_addresses
  register: iPv4_address
  ignore_errors: True

- name: Ensure mounting of udf filesystems is disabled
  shell: "lsmod | grep udf ;  modprobe -n -v udf install /bin/true"
  register: CIS_1.1.1.7
  ignore_errors: True

- name: Ensure package manager repositories are configured 
  shell: "yum repolist"
  register: CIS_1.2.1
  ignore_errors: True

- name: Ensure AIDE is installed
  shell: "rpm -q aide | grep aide-"
  register: CIS_1.3.1
  ignore_errors: True

- name: Ensure permissions on bootloader config are configured
  shell: "stat /boot/grub2/grub.cfg ; stat /boot/grub2/user.cfg"
  register: CIS_1.4.1
  ignore_errors: True

- name: Ensure prelink is disabled
  shell: "rpm -q prelink"
  register: CIS_1.5.4
  ignore_errors: True

- name: Ensure SELinux policy is configured
  shell: 'grep "SELINUXTYPE=targeted" /etc/selinux/config  ; sestatus'
  register: CIS_1.6.1.3
  ignore_errors: True

- name: Ensure message of the day is configured properly
  shell: "cat /etc/motd"
  register: CIS_1.7.1.1
  ignore_errors: True

- name: Ensure updates, patches, and additional security software are installed
  shell: 'yum check-update --security | grep -E "package|security" | tail -1'
  register: CIS_1.8
  ignore_errors: True

- name: inetd Services
  shell: "chkconfig --list"
  register: CIS_2.1
  ignore_errors: True

- name: Ensure time synchronization is in use
  shell: "rpm -q ntp ; rpm -q chrony"
  register: CIS_2.2.1.1
  ignore_errors: True

- name: Ensure NIS Client is not installed
  shell: "rpm -q ypbind"
  register: CIS_2.3.1
  ignore_errors: True

- name: Ensure IP forwarding is disabled
  shell: 'sysctl net.ipv4.ip_forward ; grep "net\.ipv4\.ip_forward" /etc/sysctl.conf /etc/sysctl.d/*'
  register: CIS_3.1.1
  ignore_errors: True

- name: Ensure bogus ICMP responses are ignored 
  shell: 'sysctl net.ipv4.icmp_ignore_bogus_error_responses ; grep "net\.ipv4\.icmp_ignore_bogus_error_responses" /etc/sysctl.conf 
/etc/sysctl.d/*'
  register: CIS_3.2.6
  ignore_errors: True

- name: Ensure IPv6 router advertisements are not accepted
  shell: 'sysctl net.ipv6.conf.all.accept_ra ;  sysctl net.ipv6.conf.default.accept_ra  ; grep "net\.ipv6\.conf\.all\.accept_ra" /etc/sysctl.conf /etc/sysctl.d/* ; grep "net\.ipv6\.conf\.default\.accept_ra" /etc/sysctl.conf /etc/sysctl.d/*'
  register: CIS_3.3.1
  ignore_errors: True

- name: Ensure TCP Wrappers is installed 
  shell: "rpm -q tcp_wrappers"
  register: CIS_3.4.1
  ignore_errors: True

- name: Ensure DCCP is disabled 
  shell: "lsmod | grep dccp"
  register: CIS_3.5.1
  ignore_errors: True

- name: Ensure default deny firewall policy
  shell: "iptables -L"
  register: CIS_3.6.2
  ignore_errors: True

- name: Ensure wireless interfaces are disabled
  shell: "iwconfig"
  register: CIS_3.7
  ignore_errors: True

- name: Ensure rsyslog Service is enabled
  shell: "systemctl is-enabled rsyslog"
  register: CIS_4.2.1.1
  ignore_errors: True

- name: Ensure rsyslog or syslog-ng is installed
  shell: "rpm -q rsyslog ; rpm -q syslog-ng"
  register: CIS_4.2.3
  ignore_errors: True

- name: Ensure cron daemon is enabled
  shell: "systemctl is-enabled crond"
  register: CIS_5.1.1
  ignore_errors: True

- name: Ensure permissions on /etc/ssh/sshd_config are configured
  shell: "stat /etc/ssh/sshd_config"
  register: CIS_5.2.1
  ignore_errors: True

- name: Ensure password hashing algorithm is SHA-512
  shell: 'egrep "^password\s+sufficient\s+pam_unix.so" /etc/pam.d/password-auth ; egrep "^password\s+sufficient\s+pam_unix.so" /etc/pam.d/system-auth'
  register: CIS_5.3.4
  ignore_errors: True

- name: Ensure password expiration is 365 days or less
  shell: "grep PASS_MAX_DAYS /etc/login.defs"
  register: CIS_5.4.1.1
  ignore_errors: True

- name: Ensure access to the su command is restricted
  shell: "grep pam_wheel.so /etc/pam.d/su ; grep wheel /etc/group"
  register: CIS_5.6
  ignore_errors: True

- name: Ensure permissions on /etc/passwd are configured 
  shell: "stat /etc/passwd"
  register: CIS_6.1.2
  ignore_errors: True

- name: Ensure password fields are not empty
  shell: 'cat /etc/shadow | awk -F: "($2 == "" ) { print $1 " does not have a password "}"'
  register: CIS_6.2.1
  ignore_errors: True

# ---------------------------------------
#               End Script
# ---------------------------------------

- name: Connection Check Report
  with_items: "{{ groups['CentOS7'] }}"
  template: 
    src: ../templates/check_connection.j2
    dest: "{{ dest_http }}/auditplay/resources/views/sub_dashboard/centos7_connection.blade.php"
  delegate_to: localhost
  ignore_errors: True

- name: Generate Report
  with_items: "{{ groups['CentOS7'] }}"
  template: 
    src: ../templates/ReportGenerator_CentOS.j2
    dest: "{{ dest_http }}/auditplay/resources/views/report/centos7/result_{{ item | regex_replace('.com') }}.blade.php"
  delegate_to: localhost
  ignore_errors: True
    # - name: copy files
    #   copy:
    #     src: "{{ src_img }}"
    #     dest: "{{ dest_http }}"
    #     owner: apache
    #     group: apache
    #     mode: 0644
    #     force: no
    #   delegate_to: localhost

#    - set_fact: current_host="{% for i in {{ item }} %} {{ i }} {% endfor %}"

